== Validation des données

=== Validation des données

* Grâce au pipe `ValidationPipe`, nous allons pouvoir valider les données entrantes
* La validation peut s'activer 
** localement à un endpoint

[source,typescript]
----
@Post()
@UsePipes(ValidationPipe)
getHello(@Body() body: User) { ... }
----

=== Validation des données

* globalement pour toute l'application

[source,typescript]
----
async function bootstrap() {
  const app = await NestFactory.create(ApplicationModule);
  app.useGlobalPipes(new ValidationPipe());
  await app.listen(3000);
}
bootstrap();
----

* localement à un paramètre

[source,typescript]
----
@Post()
getHello(@Body(new ValidationPipe()) body: User) { ... }
----

=== Validation des données

* Le validateur se base sur les modules `class-validator` et `class-transformer`

[source]
----
npm install -D class-validator class-transformer
----

=== Validation des données

* Il suffit d'ajouter des décorateurs sur vos models

[source,typescript]
----
import { IsString, IsInt, IsEmail, IsDate } from 'class-validator';

export class User {
  @IsString()
  readonly name: string;

  @IsInt()
  readonly age: number;

  @IsEmail()
  readonly email: string;

  @IsDate()
  readonly birthDate: date;
}
----


=== Custom validateur

[source,typescript]
----
import { ValidatorConstraint, ValidatorConstraintInterface, ValidationArguments } from "class-validator";

@ValidatorConstraint({ 
  name: "passwordValidator", 
  async: false 
})
export class PasswordValidator implements ValidatorConstraintInterface {

    validate(password: string, args: ValidationArguments) {
        return password.length > 5;
    }
    defaultMessage(args: ValidationArguments) { 
        return "Erreur: 'password' doit être plus compliqué 😨";
    }
}

/**
@Validate(PasswordValidator)
readonly password: string;
 */
----


=== À vous de jouer !

* Activez la validation de manière globale à l'application 
* Ajouter les contraintes suivantes sur votre classe Beer
** `id` doit être un `number`
** `label` doit être une `string`
** `description` doit être une `string`, avec un taille entre 10 et 80 caractères
** `image` doit être une `string`, et se terminer par un extension valide (via un custom validateur)
** `price` doit être une `number`, compris entre 0 et 100
** `stock` doit être une `entier`
`
